CREATE TABLE mytable(
   id       INTEGER  NOT NULL PRIMARY KEY 
  ,name     VARCHAR(28) NOT NULL
  ,aka      VARCHAR(17) NOT NULL
  ,house    VARCHAR(10) NOT NULL
  ,blood    VARCHAR(11) NOT NULL
  ,wand     VARCHAR(40) NOT NULL
  ,patronus VARCHAR(19) NOT NULL
  ,pic      VARCHAR(263) NOT NULL
);
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (1,'Harry James Potter','The Chosen One','Gryffindor','Half-blood','11", Holly, phoenix feather core','Stag','https://www.google.com/search?q=harry+potter+img&rlz=1C5CHFA_enUS823US823&tbm=isch&source=iu&ictx=1&fir=BHPBgPs7NgUJzM%252CKRV65mpSLaUVBM%252C_&vet=1&usg=AI4_-kRO7WUKqnp1McvlWDLKFfoA4BEn0g&sa=X&ved=2ahUKEwjIwrj4uIbyAhUSvJ4KHQXgDUMQ9QF6BAgTEAE#imgrc=BHPBgPs7NgUJzM');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (2,'Tom Riddle','Lord Voldemort','Slytherin','Half-blood','13½", Yew, phoenix feather core','none','https://static.wikia.nocookie.net/harrypotter/images/a/aa/Voldemort_Headshot_DHP1.png/revision/latest/scale-to-width-down/350?cb=20161203031453');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (3,'Professor Albus Dumbledor','Professor','Gryffindor','Half-blood','15", Elder, Thestral tail hair core','Phoenix','https://static.wikia.nocookie.net/harrypotter/images/4/40/Albus_Dumbledore_%28HBP_promo%29_3.jpg/revision/latest/scale-to-width-down/350?cb=20150822232849');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (4,'Draco Malfoy','Malfoy','Slytherin','Pure-blood','10", Hawthorn, unicorn hair','none','https://static.wikia.nocookie.net/harrypotter/images/7/7e/Draco_Malfoy_TDH.png/revision/latest/scale-to-width-down/350?cb=20180116013508');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (5,'Ronald Weasley','Ron','Gryffindor','Pure-blood','14", Willow, unicorn tail hair','Jack Russel terrier','https://static.wikia.nocookie.net/harrypotter/images/8/85/Ron_Weasley.jpg/revision/latest/scale-to-width-down/350?cb=20101104210200');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (6,'Hermione Jean Granger','Queen Slug','Gryffindor','Muggle-born','10¾", vine wood, dragon heartstring core','Otter','https://static.wikia.nocookie.net/harrypotter/images/3/34/Hermione_Granger.jpg/revision/latest?cb=20210522145306');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (7,'Professor Severus Snape','Half-Blood Prince','Slytherin','Half-blood','Unknown','Doe','https://static.wikia.nocookie.net/harrypotter/images/a/a3/Severus_Snape.jpg/revision/latest/scale-to-width-down/335?cb=20150307193047');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (8,'Rubeus Hagrid','Hagrid','Gryffindor','Half-giant','16", Oak, unknown core','none','https://static.wikia.nocookie.net/harrypotter/images/f/fe/Rubeus_Hagrid.png/revision/latest/scale-to-width-down/350?cb=20161123044204');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (9,'Luna Lovegood','Loony Lovegood','Ravenclaw','Pure-blood','Unknown','Hare','https://static.wikia.nocookie.net/harrypotter/images/e/ed/Luna_Lovegood.jpg/revision/latest/scale-to-width-down/336?cb=20160902165706');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (10,'Ginerva Weasley','Ginny','Gryffindor','Pure-blood','Unknown','Horse','https://static.wikia.nocookie.net/harrypotter/images/8/8b/Ginny_Weasley_hbp_promo.jpg/revision/latest/scale-to-width-down/350?cb=20090317022440');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (11,'Professor Minerva McGonagall','n/a','Gryffindor','Half-blood','9½", Fir, dragon heartstring','Cat','https://static.wikia.nocookie.net/harrypotter/images/6/65/ProfessorMcGonagall-HBP.jpg/revision/latest/scale-to-width-down/350?cb=20100612114856');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (12,'Neville Longbottom','n/a','Gryffindor','Pure-blood','13", Cherry, unicorn hair','Non-corporeal','https://static.wikia.nocookie.net/harrypotter/images/0/04/Harry-potter-and-the-deathly-hallowspart-2.jpg/revision/latest/scale-to-width-down/350?cb=20161120035218');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (13,'Bellatrix Lestrange','Bella','Slytherin','Pure-blood','12¾", Walnut, dragon heartstring','none','https://static.wikia.nocookie.net/harrypotter/images/1/14/BellatrixLestrange.png/revision/latest/scale-to-width-down/295?cb=20171101034243');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (14,'Sirius Black','Padfoot','Gryffindor','Pure-blood','Unknown','Non-corporeal','https://static.wikia.nocookie.net/harrypotter/images/b/bc/OOTP_promo_front_closeup_Sirius_Black.jpg/revision/latest/scale-to-width-down/335?cb=20150918055024');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (15,'Fred Weasley','Freddie','Gryffindor','Pure-blood','Unknown','Magpie','https://static.wikia.nocookie.net/harrypotter/images/9/90/Fred_HS_TDH_promo.jpg/revision/latest/scale-to-width-down/350?cb=20161119235258');
INSERT INTO mytable(id,name,aka,house,blood,wand,patronus,pic) VALUES (16,'Remus Lupin','Romulus','Gryffindor','Half-blood','10¼", Cypress, unicorn hair','Wolf','https://static.wikia.nocookie.net/harrypotter/images/e/e2/Remus_Lupin_Deathly_Hallows_promo_image.jpg/revision/latest/scale-to-width-down/350?cb=20161119235913');
